package dev.mikepenz.composebuddy.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies

object RegistryGenerator {
    fun generate(codeGenerator: CodeGenerator, previews: List<PreviewInfo>) {
        val file = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = true),
            packageName = "dev.mikepenz.composebuddy.device",
            fileName = "BuddyPreviewRegistryImpl",
        )

        val entries = previews.joinToString(",\n        ") { p ->
            val configs = p.configs.joinToString(",\n                ") { c ->
                val widthDp = if (c.widthDp > 0) c.widthDp else 360
                val heightDp = if (c.heightDp > 0) c.heightDp else 640
                val apiLevel = if (c.apiLevel > 0) c.apiLevel else 34
                val darkMode = (c.uiMode and 0x20) != 0
                """dev.mikepenz.composebuddy.device.model.PreviewConfig(
                widthDp = $widthDp,
                heightDp = $heightDp,
                locale = "${c.locale}",
                fontScale = ${c.fontScale}f,
                darkMode = $darkMode,
                showBackground = ${c.showBackground},
                backgroundColor = ${c.backgroundColor}L,
                apiLevel = $apiLevel,
            )"""
            }

            """"${p.fqn}" to dev.mikepenz.composebuddy.device.model.BuddyPreviewEntry(
            fqn = "${p.fqn}",
            displayName = "${p.displayName}",
            configs = listOf($configs),
            composable = { config -> ${p.packageName}.${p.functionName}Instrumented(config) },
        )"""
        }

        val emptyOrEntries = if (previews.isEmpty()) "emptyMap()" else "mapOf(\n        $entries\n    )"

        file.bufferedWriter().use { w ->
            w.write(
                """
// AUTO-GENERATED by compose-buddy-device-ksp. DO NOT EDIT.
package dev.mikepenz.composebuddy.device

object BuddyPreviewRegistryImpl : BuddyPreviewRegistry {
    override val previews: Map<String, dev.mikepenz.composebuddy.device.model.BuddyPreviewEntry> = $emptyOrEntries
}
""".trimIndent()
            )
        }
    }
}
