package dev.mikepenz.composebuddy.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies

object WrapperGenerator {
    fun generate(codeGenerator: CodeGenerator, previews: List<PreviewInfo>) {
        val byPackage = previews.groupBy { it.packageName }
        for ((pkg, pkgPreviews) in byPackage) {
            val file = codeGenerator.createNewFile(
                dependencies = Dependencies(aggregating = false),
                packageName = pkg,
                fileName = "BuddyInstrumentedWrappers",
            )
            file.bufferedWriter().use { w ->
                w.write("// AUTO-GENERATED by compose-buddy-device-ksp. DO NOT EDIT.\n")
                w.write("package $pkg\n\n")
                w.write("import androidx.compose.runtime.Composable\n")
                w.write("import dev.mikepenz.composebuddy.device.BuddyInstrumentationWrapper\n")
                w.write("import dev.mikepenz.composebuddy.device.model.PreviewConfig\n\n")
                for (p in pkgPreviews) {
                    w.write("@Composable\n")
                    w.write("internal fun ${p.functionName}Instrumented(config: PreviewConfig) {\n")
                    w.write("    BuddyInstrumentationWrapper(config, previewFqn = \"${p.fqn}\") {\n")
                    if (p.previewParameter != null) {
                        // For @PreviewParameter functions, instantiate the provider and use the first value
                        w.write("        val provider = ${p.previewParameter.providerFqn}()\n")
                        w.write("        val value = provider.values.first()\n")
                        w.write("        ${p.functionName}(${p.previewParameter.paramName} = value)\n")
                    } else {
                        w.write("        ${p.functionName}()\n")
                    }
                    w.write("    }\n")
                    w.write("}\n\n")
                }
            }
        }
    }
}
