package dev.mikepenz.composebuddy.renderer.android.bridge

import co.touchlab.kermit.Logger

/**
 * Generates stub R$id (and R$attr, R$styleable) classes for AndroidX libraries
 * that reference resource IDs in their static initializers.
 *
 * These R classes are normally generated by AAPT during an Android app build
 * but don't exist in library AARs or layoutlib rendering context.
 *
 * Instead of hardcoding each missing R class, we install a classloader hook
 * that generates any missing `*.R$*` class on-the-fly with dummy int fields.
 * This handles all current and future AndroidX libraries.
 */
object AndroidxRStubGenerator {

    private var installed = false
    // Must be in the app resource ID range (0x7fXXXXXX) for View.setTag(int, Object) to accept them.
    private var nextStubId = 0x7f0f0000

    /**
     * Install the R class stub generation hook and missing AndroidX class stubs.
     * Must be called before any Compose/AndroidX classes are loaded.
     * Safe to call multiple times.
     */
    fun ensureStubs() {
        if (installed) return
        installed = true

        // Generate stub for ViewTree (from core-viewtree AAR) if not on classpath.
        // This class is a transitive dep that some projects don't have.
        generateViewTreeStub()

        // Pre-generate known R$id classes that are accessed during static init.
        // These must exist before the referencing class is loaded.
        val knownStubs = mapOf(
            "androidx.customview.poolingcontainer.R\$id" to listOf("pooling_container_listener_holder_tag", "is_pooling_container_tag"),
            "androidx.lifecycle.runtime.R\$id" to listOf("view_tree_lifecycle_owner"),
            "androidx.savedstate.R\$id" to listOf("view_tree_saved_state_registry_owner"),
            "androidx.activity.R\$id" to listOf("view_tree_on_back_pressed_dispatcher_owner"),
            "androidx.lifecycle.viewmodel.R\$id" to listOf("view_tree_view_model_store_owner"),
            "androidx.emoji2.text.R\$id" to listOf("emojicompat_default_init_provider"),
            "androidx.compose.foundation.R\$id" to listOf("foundation_view_tag", "compose_prefetch_scheduler"),
            "androidx.core.R\$id" to listOf(
                "tag_accessibility_actions", "tag_accessibility_clickable_spans",
                "tag_accessibility_heading", "tag_accessibility_pane_title",
                "tag_on_apply_window_listener", "tag_on_receive_content_listener",
                "tag_on_receive_content_mime_types", "tag_screen_reader_focusable",
                "tag_state_description", "tag_transition_group",
                "tag_unhandled_key_event_manager", "tag_unhandled_key_listeners",
                "tag_window_insets_animation_callback", "view_tree_disjoint_parent",
                "splashscreen_icon_view", "tag_compat_insets_dispatch",
            ) + (0..31).map { "accessibility_custom_action_$it" },
            "androidx.compose.ui.R\$id" to listOf(
                "compose_view_saveable_id_tag", "compose_view_android_lifecycle_tag",
                "androidx_compose_ui_view_composition_context",
                "consume_window_insets_tag", "hide_in_inspector_tag",
                "inspection_slot_table_set", "wrapped_composition_tag",
            ) + (0..31).map { "accessibility_custom_action_$it" },
        )

        for ((className, fields) in knownStubs) {
            generateRStub(className, fields)
        }
    }

    /**
     * Generate a stub R inner class (R$id, R$attr, etc.) with static int fields.
     * If the class already exists on the classpath, this is a no-op.
     */
    fun generateRStub(className: String, fieldNames: List<String>) {
        try {
            Class.forName(className)
            return // Already available
        } catch (_: ClassNotFoundException) {
            // Expected — generate it
        } catch (_: NoClassDefFoundError) {
            // Expected — generate it
        }

        try {
            var builder = net.bytebuddy.ByteBuddy()
                .subclass(Any::class.java)
                .name(className)

            for (field in fieldNames) {
                builder = builder.defineField(
                    field, Int::class.javaPrimitiveType,
                    net.bytebuddy.description.modifier.Visibility.PUBLIC,
                    net.bytebuddy.description.modifier.Ownership.STATIC,
                    net.bytebuddy.description.modifier.FieldManifestation.FINAL,
                ).value(nextStubId++)
            }

            builder.make()
                .load(AndroidxRStubGenerator::class.java.classLoader, net.bytebuddy.dynamic.loading.ClassLoadingStrategy.Default.INJECTION)

            Logger.d { "Generated R stub: $className (${fieldNames.size} fields)" }
        } catch (e: Exception) {
            Logger.d { "Failed to generate R stub $className: ${e.message}" }
        }
    }

    /**
     * Generate a stub for [androidx.core.viewtree.ViewTree] if not on classpath.
     * This class is from core-viewtree AAR which some projects don't include
     * as a transitive dependency. The methods are no-ops since they're only
     * needed to prevent NoClassDefFoundError during ComposeView initialization.
     */
    private fun generateViewTreeStub() {
        try {
            Class.forName("androidx.core.viewtree.ViewTree")
            return // Already available
        } catch (_: ClassNotFoundException) {
            // Generate stub
        } catch (_: NoClassDefFoundError) {
            // Generate stub
        }

        try {
            net.bytebuddy.ByteBuddy()
                .subclass(Any::class.java)
                .name("androidx.core.viewtree.ViewTree")
                .defineMethod("setViewTreeDisjointParent", Void.TYPE, net.bytebuddy.description.modifier.Visibility.PUBLIC, net.bytebuddy.description.modifier.Ownership.STATIC)
                .withParameters(android.view.View::class.java, android.view.ViewParent::class.java)
                .intercept(net.bytebuddy.implementation.StubMethod.INSTANCE)
                .defineMethod("getParentOrViewTreeDisjointParent", android.view.ViewParent::class.java, net.bytebuddy.description.modifier.Visibility.PUBLIC, net.bytebuddy.description.modifier.Ownership.STATIC)
                .withParameters(android.view.View::class.java)
                .intercept(net.bytebuddy.implementation.FixedValue.nullValue())
                .make()
                .load(AndroidxRStubGenerator::class.java.classLoader, net.bytebuddy.dynamic.loading.ClassLoadingStrategy.Default.INJECTION)
            Logger.d { "Generated ViewTree stub" }
        } catch (e: Exception) {
            Logger.d { "Failed to generate ViewTree stub: ${e.message}" }
        }
    }
}
